const mime = {
    'css': 'text/css',
    'gif': 'image/gif',
    'html': 'text/html',
    'js': 'text/javascript',
    'tiff': 'image/tiff',
    'xml': 'text/xml',
    'json': 'application/json',
    'txt': 'text/plain',
    'ico': 'image/x-icon',
    'jpeg': 'image/jpeg',
    'jpg': 'image/jpeg',
    'png': 'image/png',
    'svg': 'image/svg+xml',
    'pdf': 'application/pdf',
    'wav': 'audio/x-wav',
    'flac': 'audio/x-flac',
    'wma': 'audio/x-ms-wma',
    'mp3': 'audio/mpeg',
    'wmv': 'video/x-ms-wmv',
    'mp4': 'video/x-ms-mp4',
    'mov': 'video/quicktime',
    'avi': 'video/x-msvideo',
    'mpg': 'video/mpeg',
    'mpeg': 'video/mpeg',
    'mpe': 'video/mpeg',
    'mpa': 'video/mpeg',
    'mp2': 'video/mpeg',
    'swf': 'application/x-shockwave-flash',
    'zip': 'application/zip',
    'tar': 'application/x-tar',
    'gz': 'application/x-hdf',
    'gtar': 'application/x-gtar',
    'tgz': 'application/x-compressed',
    'ppt': 'application/vnd.ms-powerpoint',
    'pptx': 'application/vnd.ms-powerpoint',
    'xls': 'application/vnd.ms-excel',
    'xlsx': 'application/vnd.ms-excel',
    'doc': 'application/msword',
    'docx': 'application/msword',
    'dll': 'application/x-msdownload',
    'bin': 'application/octet-stream',
    'exe': 'application/octet-stream',
};

module.exports = {
    mime,
};